### ISSUE TITLE
How to invoke webmethods flow services from the Bootstrap UI?

### ISSUE THREAD

**Issue by patninad** [ibm-wm-transition/webmethods-integrationserver-demo-bootstrap-ui#2]
Hi,

Thank you so much for the demo. I think this is very useful given that there are not many good UI options within the webMethods platform. 

I just want to ask how to invoke flow services from the Bootstrap UI. Do the normal DSP ways of invoking services work with Bootstrap?

Thanks and Regards,
Ninad Patil

**Comment by christophjahn** [comment]
Yes, all the DSP tags work. At the end of the day Bootstrap adds just CSS and JavaScript, both of which are basically transparent to the IS' built-in web server. So the DSP tags are executed on the server, and the Bootstrap part is executed in the web browser.

Hope that helps.
